export const projectList = [
  {
    title: "CoofOff 8.0 - Admin Portal",
    redirect: "https://github.com/CodeChefVIT/cookoff23-admin",
    image: [
      "/assets/thumbnails/Cookoff-Admin/1.png",
      "/assets/thumbnails/Cookoff-Admin/2.png",
      "/assets/thumbnails/Cookoff-Admin/3.png",
      "/assets/thumbnails/Cookoff-Admin/4.png",
      "/assets/thumbnails/Cookoff-Admin/5.png",
      "/assets/thumbnails/Cookoff-Admin/6.png",
    ],
    techstack: "NextJS • TailwindCSS • Framer-Motion",
  },
  {
    title: "CoofOff 8.0 - Admin Portal",
    redirect: "https://github.com/CodeChefVIT/cookoff23-admin",
    image: [
      "/assets/thumbnails/Cookoff-Admin/1.png",
      "/assets/thumbnails/Cookoff-Admin/2.png",
      "/assets/thumbnails/Cookoff-Admin/3.png",
      "/assets/thumbnails/Cookoff-Admin/4.png",
      "/assets/thumbnails/Cookoff-Admin/5.png",
      "/assets/thumbnails/Cookoff-Admin/6.png",
    ],
    techstack: "NextJS • TailwindCSS • Framer-Motion",
  },
  {
    title: "CoofOff 8.0 - Admin Portal",
    redirect: "https://github.com/CodeChefVIT/cookoff23-admin",
    image: [
      "/assets/thumbnails/Cookoff-Admin/1.png",
      "/assets/thumbnails/Cookoff-Admin/2.png",
      "/assets/thumbnails/Cookoff-Admin/3.png",
      "/assets/thumbnails/Cookoff-Admin/4.png",
      "/assets/thumbnails/Cookoff-Admin/5.png",
      "/assets/thumbnails/Cookoff-Admin/6.png",
    ],
    techstack: "NextJS • TailwindCSS • Framer-Motion",
  },
  {
    title: "CoofOff 8.0 - Admin Portal",
    redirect: "https://github.com/CodeChefVIT/cookoff23-admin",
    image: [
      "/assets/thumbnails/Cookoff-Admin/1.png",
      "/assets/thumbnails/Cookoff-Admin/2.png",
      "/assets/thumbnails/Cookoff-Admin/3.png",
      "/assets/thumbnails/Cookoff-Admin/4.png",
      "/assets/thumbnails/Cookoff-Admin/5.png",
      "/assets/thumbnails/Cookoff-Admin/6.png",
    ],
    techstack: "NextJS • TailwindCSS • Framer-Motion",
  },
  {
    title: "CoofOff 8.0 - Admin Portal",
    redirect: "https://github.com/CodeChefVIT/cookoff23-admin",
    image: [
      "/assets/thumbnails/Cookoff-Admin/1.png",
      "/assets/thumbnails/Cookoff-Admin/2.png",
      "/assets/thumbnails/Cookoff-Admin/3.png",
      "/assets/thumbnails/Cookoff-Admin/4.png",
      "/assets/thumbnails/Cookoff-Admin/5.png",
      "/assets/thumbnails/Cookoff-Admin/6.png",
    ],
    techstack: "NextJS • TailwindCSS • Framer-Motion",
  },
];
